Fix tides on angled boundaries, consolidate regridded of velocity and tracers, add proper body tide parameters, add MOM6's angle calculation.
CROCODILE-CESM/regional-mom6 pull request #33
Opened 2024-10-25 19:50 UTC by manishvenu

Fixes #22 

This PR address four problems/improvements in RM6:

- [ ] This addresses #22, that the tidal regridding wasn't taking into account a curved boundary. This is because I didn't correctly convert the rotation code from GFDL's NWA25 (See the changes to the ap2ep section)
- [ ] Add @gsiejo's body tides MOM_override changes. We had some defaults, but this should make it actually legit
- [ ]  Merge the velocity/tracers and tides regridding. They were originally seperated because they were developed independently. We've decided to convert the tides regridding into the generic one...
- [ ] MOM6 has its own way of calculating angle that doesn't read the input hgrid's angle. This PR adds the MOM6 calculation of angles to the hgrid...

Major Changes:

1. Add the rotation to the tides regridder (that was previously missing)

Minor Changes:

1. Minor bug in setup_run_directory when it checked to make sure tidal files exist

2024-11-01 19:33 UTC, manishvenu commented
Because this is such a big change... I'm doing dev in a branch of crr (there's no reason for it to be there other than version control) https://github.com/CROCODILE-CESM/crocodile-regional-ruckus/tree/support_tides_clean_branch/tides_dev

Currently a good way through the merging and some progress on the tides bug.

2024-12-20 17:10 UTC, manishvenu commented
@alperaltuntas The tests for this PR `(test_regridding.py)` use dummy data fixtures in `conftest.py`. They do a good job of checking the properties of all the functions in `regridding.py`, but are somewhat hardcoded (Ex. I know what the variable names in the dummy data are called, so I just directly call those.). Do you think its worth taking the time here to make it more like PBT/less hard coded, or add that into another PR. I'm thinking that most of the testing needs to be changed out of hardcoding, and we need to add a decent amount of testing as well. It may be worth it to have a big testing PR. A lot of the bigger functions like setup_inital_condition, setup_bathymetry are just smoke tests currently, and we do need to think about if we want to test with MOM6.

Otherwise, other than the corner points and 3 points at the "coasts" needing to be real values in the original tidal bug, this PR is pretty much wrapped up.

2024-12-21 20:37 UTC, manishvenu commented
Quick Flag:  The Github tests were failling in python 3.12 in test_expt_class::test_ocean_forcing(). This was not changed in the PR, but seems to be a threading issue. Setting dask to single-threaded was a workaround for this. Please let me know if this raises a red flags we have to address!

2025-01-09 22:50 UTC, alperaltuntas requested changes

2025-01-09 22:50 UTC, alperaltuntas commented on regional_mom6/regional_mom6.py
> +        if rotational_method == rot.RotationMethod.GIVEN_ANGLE:
This `rotational_method` if statement appears so many times in the module, so I wonder if there is an opportunity for a code reuse by generically writing it as a class method or something, and calling it instead of rewriting the whole block every time( e.g., code segments 3072-3102, 3486-3510,  and more.)

2025-01-09 22:50 UTC, alperaltuntas commented on regional_mom6/regridding.py
> +def create_regridder(
Not sure why we need this function as an extra layer indirection. Why not call xe.Regridder directly?

2025-01-10 18:40 UTC, manishvenu commented on regional_mom6/regional_mom6.py
>                  "Only rectangular boundaries are supported by this method."
Resolved

2025-01-10 18:41 UTC, manishvenu commented on regional_mom6/regional_mom6.py
>              # If the GLORYS ocean_state has already created segments, we don't create them again.
Resolved

2025-01-10 18:42 UTC, manishvenu commented on regional_mom6/regridding.py
> +def create_regridder(
This is a good point, I had originally made it this way to we can standardize defaults (like interpolation method like bilinear, so that each regridding function starts with that). It does just wrap the xesmf.Regridder after development. Do you think we should just remove this function?

2025-01-10 18:44 UTC, manishvenu commented on regional_mom6/regional_mom6.py
> +            tidal_filename: Name of the tpxo product that's used in the tidal_filename. Should be h_tidal_filename, u_tidal_filename
Resolved

2025-01-10 18:46 UTC, manishvenu commented on regional_mom6/regional_mom6.py
> +                None,
Because I called it from the class name ... which I initially thought would fill the self arg and didn't,I filled it with None. However, there is no reason for this function to be in the segment class, I will move it to utils instead

2025-01-10 18:51 UTC, manishvenu commented on regional_mom6/regional_mom6.py
> +                None,
Resolved

2025-01-10 20:44 UTC, manishvenu commented on regional_mom6/regional_mom6.py
Resolved

2025-01-10 20:50 UTC, manishvenu commented on regional_mom6/regional_mom6.py
> +from . import regridding as rgd
Resolved

2025-01-10 20:53 UTC, manishvenu commented on regional_mom6/regional_mom6.py
> +        renamed_hgrid = self.hgrid  # This is not a deep copy
Yeah, thanks, that's true. Since we're just adding fields and not saving the hgrid back to file, I'll just explictly use self.hgrid instead of deep copying.

2025-01-10 20:54 UTC, manishvenu commented on regional_mom6/regional_mom6.py
> +        renamed_hgrid = self.hgrid  # This is not a deep copy
Resolved

2025-01-10 20:56 UTC, manishvenu commented on regional_mom6/utils.py
> +    if not np.all(hgrid.y == hgrid.y[:, 0].values[:, np.newaxis]):
Oh yeah, I saw that -> I'll replace the function with that one.

2025-01-10 20:58 UTC, manishvenu commented on regional_mom6/utils.py
> +    if not np.all(hgrid.y == hgrid.y[:, 0].values[:, np.newaxis]):
Resolved.

2025-01-13 18:19 UTC, manishvenu commented on regional_mom6/regional_mom6.py
> +        if rotational_method == rot.RotationMethod.GIVEN_ANGLE:
Resolved with function `get_rotation_angle` in `rotation.py`

2025-01-13 18:20 UTC, manishvenu commented on regional_mom6/regridding.py
> +def create_regridder(
@alperaltuntas Other than this comment, this PR is ready for another round of review

2025-01-17 16:58 UTC, manishvenu commented
Solution to Original Bug: 
1. Default: Fill NaNs with zeroes by default in BC Files 
2. When bathymetry is supplied, create a land mask for the boundaries with certain exceptions (corner points & 3 points at the coast must be real).

2025-01-17 18:13 UTC, merged

2025-01-17 18:22 UTC, manishvenu commented
FYI: Discussion with Alper offline, decided to merge